
spring:
  profiles:
    default: local
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jwt:
    header: Authorization
    secret: ZXJzdFJlc3RBUElBcHBsaWNhdGlvbg==
  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

# CORS
cors.allow.method: GET, POST, PATCH, DELETE, OPTIONS
# ?? ??? ?? ${user.home} => /Users/???
file.upload.path: ${user.home}/Documents/upload/erst/uploads

---
spring:
  config:
    activate:
      on-profile: prod
  # Spring DataSource MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://3.38.151.87:3306/erst?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: erst
    password: ers0212!@

---
spring:
  config:
    activate:
      on-profile: local
  # Spring DataSource MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://219.248.82.98:12304/dev_test?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: dev_user
    password: ers0212!@

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 400
        use_sql_comments: true
    open-in-view: false


